# Generated by Django 6.0.4 on 2026-05-07 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0002_commentvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussioncomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='discussions.discussioncomment'),
        ),
    ]
