# Generated by Django 6.0.4 on 2026-05-07 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shift_coverage', '0002_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
